[package]
name = "fogo_program"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "fogo_program"

[dependencies]
solana-program = "1.18.26"

[features]
no-entrypoint = []
