name: Build SBF From Source

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Solana SBF Rust Toolchain
        run: |
          rustup toolchain install nightly-2023-04-25
          rustup default nightly-2023-04-25
          rustup component add rust-src --toolchain nightly-2023-04-25

      - name: Add SBF Target
        run: rustup target add sbf-solana-solana --toolchain nightly-2023-04-25

      - name: Fetch dependencies
        run: cargo fetch

      - name: Build Program (SBF)
        run: cargo +nightly-2023-04-25 build-sbf --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fogo_sbf
          path: target/deploy/*.so
